AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable
  Include:
    - '**/*.rb'
  Exclude:
    - '.git/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/RegexpLiteral:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Metrics/MethodLength:
  Max: 25
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 35
