name: CI Rubocop and Rspec check

on: [push, pull_request]

jobs:
  build:
    name: Run rubocop and Rspec
    runs-on: ubuntu-latest

    steps:
      # Ruby setup
      - uses: actions/checkout@v2
      - name: Set up Ruby Version
        uses: actions/setup-ruby@v1
      - name: Run bundle install
        run: bundle install
      - name: Run tests
        run: rspec

      # Upload coverage results
      - name: Upload coverage results
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: coverage-report
          path: coverage
